function job=build_job(paths,onsets, duration,rp,dest,mask, covariable, TR)
                        
% FUNCTION build_job.m 
% Builds the job structure that will later be executed by spm_jobman.m



     %=======================================================================
    % Build job
    %=======================================================================
    timing  =   struct(                                                    ...
        'units',        'scans',                                            ...
        'RT',           TR/1000,                                                  ...
        'fmri_t',       16,                                                 ...    
        'fmri_t0',      1                                                   ...        
        );
    onsets  =   onsets;
    cond    =   struct(                                                     ...
        'name',         'Fmri_session',                                     ...
        'onset',        onsets,                                             ...
        'duration',     duration,                                           ...
        'tmod',         0,                                                  ...
        'pmod',         struct([]),                                         ...
        'orth',         []                                                  ...
        );
    multireg        =   '';
    multireg        =   cellstr(rp);
    vals            =   {};
    str             =   {};
    rgss             =  struct([]);
    if ~isempty(covariable) && (nnz(covariable)>0)
        for i=1:size(covariable,2)
           str{i}   =   ['cov' num2str(i)]; 
           vals{i}  =   covariable(:,i);
        end
        rgss  =   struct('name',str,'val',vals); 
    end
    sess        =   struct(                                                 ...
        'scans',        {paths},                                            ...
        'cond',         cond,                                               ...
        'multi',        {cell(1)},                                          ...    
        'regress',      rgss,                                            ...        
        'multi_reg',    {multireg},                                         ...
        'hpf',          128                                                 ...
        );
    fid = fopen(mask,'r');
    if fid<1
        em  =   {''};
    elseif ischar(mask)
        em  =   cellstr(mask); 
    end
    
    %bases = struct('hrf',struct('derivs',[1,1]));
    bases   =   struct('fir',struct('length',1,'order',1));
%     bases = struct('hrf',struct('derivs',[0,0]));
    job     =   struct(                                                            ...
        'spmmat',       {cellstr([dest filesep 'SPM.mat'])},                ...
        'dir',          {cellstr(dest)},                                    ...
        'scans',        {paths},                                            ...
        'timing',       timing,                                             ...   
        'sess',         sess,                                               ...
        'fact',         struct([]),                                         ...
        'bases',        bases,                                              ...
        'volt',         1,                                                  ...
        'global',       'None',                                             ...
        'mask',         {em},                                               ...
        'cvi',          'AR(1)',                                            ...
        'mthresh',      1                                                 ...        
    );    
    save('job.mat','job');

end